### ISSUE TITLE
Runtime Error: cuda error: out of memory

### ISSUE THREAD

**Issue by Yashrt263** [ekosman/AnomalyDetectionCVPR2018-Pytorch#87]
PLEASE HELP!!
I have installed Cuda Version 10.2.
I ran into this error.

![knkjm](https://user-images.githubusercontent.com/86078569/122680904-40e4a200-d20f-11eb-9171-eee4802e9271.PNG)

**Comment by ekosman** [comment]
Your GPU is out of memory. Do you run other processes that utilize your GPU?

**Comment by Yashrt263** [comment]
@ekosman No, only the terminal was running at the time and no background processes were using the gpu. The Task Manager showed 80-90% utilisation of the gpu. I have GTX 1050ti 4 GB.

**Comment by ekosman** [comment]
I'd suggest to reduce the batch size.

**Comment by Yashrt263** [comment]
@ekosman Reducing the batch size from 8 to 4 worked for me. Thanks!

**Comment by Yashrt263** [comment]
@ekosman Training the model for 20000 epochs is taking too long (approx. 15 seconds per iteration -- It might take around 80 hrs to complete 20000 epochs). Task manager shows that my CPU and Memory are not being fully utilized (CPU = 30% and Ram = 35%).

My computer specs-
CPU = i5-8300H 
GPU = GTX 1050ti 4gb
Ram = 16 GB 2666Mhz
1 TB Samsung Nvme SSD

Are these specs not enough? Is there any way I could speed up the Training process?

**Comment by ekosman** [comment]
@Yashrt263  Sorry for the delay, I was busy this week

The methodology described in the original work limits the usage of resources. Each update is based on features sampled from 60 videos only, which limits the usage of RAM and CPU. I think I can enhance the data loading code by caching the features instead of reloading it every time a feature is sampled, but I can't guarantee that it'll be done this weekend.

**Comment by ekosman** [comment]
@Yashrt263 I merged an improvement now. It should run way faster now. 20K iterations take ~45 minutes on my MAC:

```
2021-06-24 21:01:37,062 Epoch 0/2      Iteration 19970/20000    loss: 0.6897591948509216    Time: 0.134 seconds/iteration
2021-06-24 21:01:39,690 Epoch 0/2      Iteration 19980/20000    loss: 0.7821298241615295    Time: 0.134 seconds/iteration
2021-06-24 21:01:41,043 Epoch 0/2      Iteration 19990/20000    loss: 0.7319804430007935    Time: 0.134 seconds/iteration
2021-06-24 21:01:42,633 Save the model after epoch 0
2021-06-24 21:01:42,645 
============================================================================================================================
Epoch 0/2     Train loss: 0.8981562509655953        time: 0:44:39.338069
============================================================================================================================
```

**Comment by Yashrt263** [comment]
@ekosman Thank you Sir.

**Comment by Yashrt263** [comment]
**@ekosman Please Help!!**

I tried to run the video_demo.py file but it isn't showing any results. 
It allows me to browse for videos but shows a blank graph after execution.

![qw12](https://user-images.githubusercontent.com/86078569/123860697-dd135500-d943-11eb-816b-2b131b2d8eab.PNG)


![qw23](https://user-images.githubusercontent.com/86078569/123860454-8d348e00-d943-11eb-86cd-7bf1a112547e.PNG)

**Comment by ekosman** [comment]
@Yashrt263 
Thank you for reporting. I've patched a fix for this. Next time, I'd appreciate it if you open a separate issue so that I can keep track of the issues.

**Comment by Yashrt263** [comment]
@ekosman Thanks for helping.

**Comment by ekosman** [comment]
I'm closing this since it seems to be solved.
